# Filterbank config
filterbank:
  n_filters: 64
  kernel_size: 16
  stride: 8
# Network config
masknet:
  in_chan: 64
  n_src: 2
  out_chan: 64
  bn_chan: 128
  hid_size: 128
  chunk_size: 100
  hop_size: 50
  n_repeats: 6
  mask_act: 'sigmoid'
  bidirectional: true
  dropout: 0
# Training config
training:
  cont: false
  epochs: 200
  batch_size: 6
  num_workers: 6
  half_lr: yes
  early_stop: yes
  gradient_clipping: 5
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: !!float 1e-5
# Data config
data:
  task: sep_clean
  data_dir: data
  train_dir: data/wav8k/min/train-360
  valid_dir: data/wav8k/min/dev
  test_dir: data/wav8k/min/test
  sample_rate: 8000
  segment: 3
